title: <p align="center">Subanand Thiruppathi Rajan</p>
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

title: <p align="center"> Subanand Thiruppathi Rajan</p>
 

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/subanand-thiruppathi-rajan-2229224/">LinkedIn</a> |
  <a href="https://github.com/tsubanand">GitHub</a>
  </p>
  
 